- ios/Runner.xcodeproj/project.pbxproj
- lib/domain/interactor/users_interactor.dart
- lib/domain/usecases/users_usecase.dart
- lib/infrastructure/repositories/user_db_repositories_impl.dart
- lib/presentation/view/components/drawer_content.dart
- lib/presentation/view_model/users_view_model.dart
> #75 アカウント削除

- lib/domain/interactor/users_interactor.dart
- lib/domain/repositories/auth_repository.dart
- lib/domain/usecases/users_usecase.dart
- lib/infrastructure/repositories/auth_repositories_impl.dart
- lib/presentation/router/router.dart
- lib/presentation/router/router.gr.dart
- lib/presentation/view/components/app_textform.dart
- lib/presentation/view/components/drawer_content.dart
- lib/presentation/view/pages/settings/password/password_change_page.dart
- lib/presentation/view/pages/start/sign_in_page.dart
- lib/presentation/view_model/users_view_model.dart
> #72 パスワード変更機能

- ios/Podfile.lock
- lib/presentation/view/pages/root_page.dart
- lib/presentation/view_model/config_view_model.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> #88 バージョン管理バグ修正

- lib/domain/entity/enums/shared_preferences_key.dart
- lib/domain/interactor/app_interactor.dart
- lib/domain/repositories/remote_config.dart
- lib/domain/repositories/shared_preferences_repository.dart
- lib/domain/utils/string_utils.dart
- lib/infrastructure/enums/remote_config_key.dart
- lib/infrastructure/enums/shared_preferences_key.dart
- lib/infrastructure/repositories/remote_config_repository_impl.dart
- lib/infrastructure/repositories/shared_preferences_repository_impl.dart
- lib/presentation/model/search_page_model.dart
- lib/presentation/view/components/app_button.dart
- lib/presentation/view/components/update_dialog.dart
- lib/presentation/view/pages/search/search.dart
- windows/flutter/generated_plugin_registrant.cc
- しらべるページ
- config fetch追加
- configに新しい値追加
> #113 しらべるページ作成

- lib/presentation/view/components/drawer_content.dart
> #117 遷移先修正

- lib/infrastructure/repositories/remote_config_repository_impl.dart
- lib/presentation/view/pages/measurement/measurement_page.dart
- windows/flutter/generated_plugin_registrant.cc
> #86 そくていページ作成

- pubspec.lock
- test/instastructure/claude_test.dart
> #120 pubspeclockコンフリクト修正

- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- lib/infrastructure/repositories/auth_repositories_impl.dart
-権限を付与しました
https://github.com/junjun-1345/aizuchi_app/assets/107928941/69a4b625-71da-427f-b451-d1cb7ee3a0b4
> Apple Sign in バグ修正

- lib/presentation/view/pages/start/sign_in_page.dart
> #130 パスワード変更画面から戻れない 

- lib/domain/domain_module.dart
- lib/domain/interactor/daily_interactor.dart
- lib/domain/interactor/users_interactor.dart
- lib/domain/repositories/user_db_repository.dart
- lib/domain/usecases/users_usecase.dart
- lib/infrastructure/enums/shared_preferences_key.dart
- lib/infrastructure/repositories/auth_repositories_impl.dart
- lib/infrastructure/repositories/user_db_repositories_impl.dart
- lib/infrastructure/utils/handle_firebase_auth_exception.dart
- lib/presentation/router/auth_guard.dart
- lib/presentation/router/register_guard.dart
- lib/presentation/router/router.dart
- lib/presentation/state/user_state.dart
- lib/presentation/view/components/drawer_content.dart
- lib/presentation/view/pages/start/sign_up_form_check_page.dart
- lib/presentation/view/pages/start/sign_up_form_name_page.dart
- lib/presentation/view_model/users_view_model.dart
- firebase exception hundler追加
- auto router guard追加
- 登録中のガード作成
- auth関係のtry catchをviewmodelに移動
- 初期画面をsignupに
> #138 サインイン・サインアップの修正

- lib/presentation/view/pages/calender/calendar_page.dart
- lib/presentation/view/pages/log/components/carousel_tiles/days_carousel_tile.dart
- lib/presentation/view/pages/log/components/carousel_tiles/emotion_graph_tile.dart
- lib/presentation/view/pages/log/components/carousel_tiles/emotion_stock_tile.dart
- lib/presentation/view/pages/log/components/log_summary_tile.dart
- lib/presentation/view/pages/log/log_page.dart
- lib/presentation/view/pages/measurement/measurement_page.dart
- lib/presentation/view/pages/message/components/message_emotion_select_dialog.dart
- lib/presentation/view/pages/message/components/message_footer_contents.dart
- lib/presentation/view/pages/profile/components/edit_profile_dialog.dart
- lib/presentation/view/pages/profile/components/profile_tile.dart
- lib/presentation/view/pages/profile/edit_profile_page .dart
- lib/presentation/view/pages/start/components/sign_up_form_widget.dart
- lib/presentation/view/pages/start/sign_in_page.dart
- lib/presentation/view/pages/start/sign_up_form_check_page.dart
- lib/presentation/view/pages/start/sign_up_page.dart
-「日記を書く」ダイアログのオーバーフロー修正
- そくてい画面オーバーフロー修正
- プロフィール編集ページ　キーボードのオーバーフロー修正
- プロフィール確認画面　名前のオーバーフロー修正
- 会話ページ Premium誘導ボタンのオーバーフロー修正
- ログイン・ログアウト画面オーバーフロー修正
- カレンダー下部オーバーフロー修正
- ログページオーバーフロー修正
https://github.com/junjun-1345/aizuchi_app/assets/107928941/80efefed-4e91-4437-bb91-193b410d7fc6
> #149 オーバーフロー修正

- lib/presentation/router/auth_guard.dart
- lib/presentation/router/router.dart
- lib/presentation/state/user_state.dart
- lib/presentation/view/pages/start/sign_up_page.dart
- 不要なprint削除
- リンク追加
- router guard削除
> #146 サインアップページのリンク遷移先追加

- lib/presentation/router/router.dart
- lib/presentation/router/router.gr.dart
- lib/presentation/view/components/drawer_content.dart
- lib/presentation/view/pages/settings/auth/authentication_cooperation_page.dart
- lib/presentation/view/pages/settings/character/character_select_page.dart
> #125 キャラクターページ

- ios/Podfile.lock
- lib/presentation/view/pages/root_page.dart
> #144 iconを変更

- lib/domain/domain_module.dart
- lib/domain/interactor/messages_interactor.dart
- lib/infrastructure/enums/gpt_model.dart
- lib/infrastructure/enums/remote_config_key.dart
- lib/infrastructure/repositories/gpt_repository_impl.dart
- lib/presentation/model/search_page_model.dart
- lib/presentation/view/components/app_appbar.dart
- lib/presentation/view/components/web_view.dart
- lib/presentation/view/pages/calender/calendar_page.dart
- lib/presentation/view/pages/log/components/graph_contents/graph.dart
- lib/presentation/view/pages/log/log_page.dart
- lib/presentation/view/pages/measurement/measurement_page.dart
- lib/presentation/view/pages/message/components/message_emotion_select_dialog.dart
- lib/presentation/view/pages/message/limit_message_page.dart
- lib/presentation/view/pages/message/message_page.dart
- lib/presentation/view/pages/profile/current_profile_page.dart
- lib/presentation/view/pages/profile/edit_profile_page.dart
- lib/presentation/view/pages/root_page.dart
- lib/presentation/view/pages/search/search.dart
- lib/presentation/view/pages/settings/auth/authentication_cooperation_page.dart
- lib/presentation/view/pages/settings/character/character_select_page.dart
- lib/presentation/view/pages/settings/mail/mail_confirm_page.dart
- lib/presentation/view/pages/settings/notification/notification_page.dart
- lib/presentation/view/pages/settings/password/password_change_page.dart
- lib/presentation/view/pages/settings/plan/plan_page.dart
- lib/presentation/view/pages/settings/purchase/purchase_page.dart
- test/instastructure/llm_connection_test.dart
-  FIXME削除
-  ダイアログの修正
-  appbar共通化
-  グラフUI修正
-  LLMをgptオムニに変更
> #163 UI微調整

- lib/presentation/view/components/app_dialog.dart
- lib/presentation/view/pages/message/components/message_emotion_select_dialog.dart
- lib/presentation/view/pages/message/components/message_overlimit_dialog.dart
- lib/presentation/view/pages/profile/components/edit_profile_dialog.dart
- lib/presentation/view/pages/profile/components/edit_sex_dialog.dart
- lib/presentation/view/pages/search/search.dart
- surfaceTintColorを透明に変更
- テスト用のボタンをsearchPageに追加しています。Approve後、削除します。
> #141 ダイアログを白に適応

- lib/presentation/state/daily_state.dart
> #161 チャートバグ

- lib/domain/domain_module.dart
- lib/domain/interactor/messages_interactor.dart
- lib/domain/interactor/users_interactor.dart
- lib/domain/usecases/messages_usecase.dart
- lib/domain/usecases/users_usecase.dart
- lib/infrastructure/enums/remote_config_key.dart
- lib/presentation/model/remaining_limit_model.dart
- lib/presentation/state/app_state.dart
- lib/presentation/state/daily_state.dart
- lib/presentation/state/message_state.dart
- lib/presentation/state/user_state.dart
- lib/presentation/view/components/drawer_content.dart
- lib/presentation/view/pages/message/components/message_footer_contents.dart
- lib/presentation/view/pages/message/components/message_overlimit_dialog.dart
- lib/presentation/view/pages/message/message_page.dart
- lib/presentation/view_model/message_view_model.dart
- lib/presentation/view_model/subscription_view_model.dart
- 課金制度廃止後、会話制限機能のバグ修正
- remote configから制限数と制限の有無を選択できるように
> #148 課金制度廃止

- lib/presentation/state/user_state.dart
- lib/presentation/view/pages/root_page.dart
> リジェクト修正 1.0.0 (11)

- lib/presentation/view/pages/root_page.dart
> リジェクト修正 1.0.0 (12)

- lib/presentation/view/pages/log/components/carousel_tiles/emotion_stock_tile.dart
> 感情ストックのMaxY修正
